### PR TITLE
Draft: Auto update version details on new release

### PR DESCRIPTION
**Pull request by hdm23061993**
## Changes proposed

- [ ] Auto update version details on new release in plugin.yaml

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by undera** [comment]
We rely on goreleaser functionality to fill the release details. The goreleaser would crash if you try to run it with code replacements. I changed the base branch to illustrate that

**Comment by undera** [comment]
Well, it did not reproduce it, but it would if I do the release. GoReleaser takes care itself about replacements, we set it via ldflags: https://github.com/komodorio/helm-dashboard/blob/main/Makefile#L19

**Comment by undera** [comment]
Bgrrr, Makefile has nothing to do with it, goreleaser just magically picks up the version in the GH action

**Comment by hdm23061993** [comment]
How do you recommend to handle it?

**Comment by hdm23061993** [comment]
Initially i created the PR to `main` branch and it did pass all the checks

https://github.com/komodorio/helm-dashboard/pull/161

**Comment by undera** [comment]
If you download any release, you will see that the correct information is present in binary. It's only the local developer builds that miss it, which is fine IMO. Makefile has env variables supported to set the version info, if you want it.

I'm not sure what is the problem you are trying to solve.

**Comment by undera** [comment]
The only problem around versions we have is the need to change version inside `plugin.yaml` manually for each release. It would be great to have a step in release automation to update that file and commit the change.

**Comment by hdm23061993** [comment]
Gotach. Let me see if i can handle that in a different PR.
Closing this one

**Comment by hdm23061993** [comment]
Currently, how is a new release made? Using some commit or running some CI?

Can you please provide some insights?

**Comment by undera** [comment]
Current way to release is to create new tag in GH repo. This triggers fully automated release process.

**Comment by undera** [comment]
The release process is declared here: https://github.com/komodorio/helm-dashboard/blob/main/.github/workflows/release.yaml

**Comment by hdm23061993** [comment]
> The only problem around versions we have is the need to change version inside `plugin.yaml` manually for each release. It would be great to have a step in release automation to update that file and commit the change.

If we do this then what will be the trigger for release automation?

**Comment by undera** [comment]
The process will be the same. Just the commit of changing plugin.yml won't be included into release tag and will be right after tag, on main branch

**Comment by hdm23061993** [comment]
So if I understood correctly, we need a new step under `job:release` (below snippet) or a new job in `release.yaml`?

https://github.com/komodorio/helm-dashboard/blob/445bb6fa3c144f078cd74898e19f982910c479bf/.github/workflows/release.yaml#L31-L59

**Comment by hdm23061993** [comment]
Please help review the change

**Comment by undera** [comment]
Can you make this change against the `main` branch, as it is not 1.0-specific?

**Comment by hdm23061993** [comment]
Sure
I will create a new PR

**Pull request closed without merging**
