### PR TITLE
Adding more information on UI for helm test API response

### PR DESCRIPTION
**Pull request by hdm23061993**
## Fixes Issue
#115
#178 

## Changes proposed

- Migrate existing API (for `helm test`) to use object model

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

image

image

image

image

### CODE REVIEW

**Comment by undera** [comment]
here's the question: is it possible to tell if chart has tests or not, based on its properties? Then, we could expose that in a field like `hasTests` and hide the button if there are no tests

**Comment by toddtee** [comment]
> here's the question: is it possible to tell if chart has tests or not, based on its properties? Then, we could expose that in a field like `hasTests` and hide the button if there are no tests

Yep, this is a much better UX.

**Comment by hdm23061993** [comment]
I did not find any such API/command to get such details
I am checking with the helm team on slack if there is some way for it

**Comment by undera** [comment]
According to helm source code, tests are hooks of `release.HookTest` type. We have access to the list of hooks for release, thus can detect that.

**Comment by undera** [comment]
@hdm23061993 Do you plan to work more on this one?

**Comment by hdm23061993** [comment]
Thanks @undera 👍 
I will use that and implement the recommendations

**Comment by undera** [comment]
@hdm23061993 I am planning to merge 1.0 PR today. Do you want to merge this PR before 1.0 released?

**Comment by hdm23061993** [comment]
it will take me a day or two to complete this one
Do you want to take it ahead and handle the recommendation?
This way we can have the complete feature in v1.0

**Comment by undera** [comment]
Ok, I'll merge this one and will take it from there. Thanks!

**Comment by hdm23061993** [comment]
Thank you @undera 🥇

**Comment by undera** [comment]
FYI you can see the commit a made to complete it

**Comment by hdm23061993** [comment]
Reviewed
Thanks for completing the feature before release v1.0 👍

**Pull request merged**
