### PR TITLE
Implement install modal skeleton

### PR DESCRIPTION
**Pull request by ErezBiren**
Implement the skeleton for Install Modal.
This modal contains some complicated controls that are missing.
They should be implemented in a separate PR.

Implemented with hardcoded mock data for now.

image

- [x] The title of my pull request is a short description of the changes
- [x] This PR relates to some issue: #259  
- [x]  I have documented the changes made (if applicable)
- [ ]  I have covered the changes with unit tests

### CODE REVIEW

**Comment by ErezBiren** [comment]
@chad11111 please have a look.

**Comment by chad11111** [comment]
@ErezBiren please remove all unrelated files.

**Comment by chad11111** [comment]
@ErezBiren the modal doesn't open for me, I just see a gray screen.

**Comment by ErezBiren** [comment]
> remove all unrelated files.

Unrelated files have been removed.

**Comment by ErezBiren** [comment]
> @ErezBiren the modal doesn't open for me, I just see a gray screen.

I'm checking it.

**Comment by ErezBiren** [comment]
> @ErezBiren the modal doesn't open for me, I just see a gray screen.
@chad11111 
Fixed.

**Pull request merged**
