### PR TITLE
Auto increment version in plugin.yaml on a new release

### PR DESCRIPTION
**Pull request by hdm23061993**
## Changes proposed

- [X] Auto update version details on new release in plugin.yaml

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by undera** [comment]
@ronahk WDYT?

**Comment by hdm23061993** [comment]
@undera @ronahk 
Gentle reminder

**Comment by ronahk** [comment]
@undera this would not work since the first step in the pipeline checks if the plugin version matches the tag name. We can discuss another possibility for optimizing the pipeline but this change is a bit problematic as is.

**Comment by undera** [comment]
From my understanding, we need a very simple addition to current release automation: after goreleaser step is complete, a step that will take the tag name, cut 'v' off it and place it into plugin.yaml, then commit the change.

**Comment by hdm23061993** [comment]
@ronahk Feel free to update the commit logic if you have better approach

**Comment by undera** [comment]
Closing in favor of #202

**Pull request closed without merging**
