### PR TITLE
fixbug: ChartAndVersion did not handle chart version correct in some case

### LINKED ISSUE #95: ChartAndVersion func may have wrong result in some case.
https://github.com/komodorio/helm-dashboard/blob/cf407c63a23e25cd15878661c2067458a14979b3/pkg/dashboard/utils/utils.go#L19

```
func ChartAndVersion(x string) (string, string, error) {
	lastInd := strings.LastIndex(x, "-")
	if lastInd < 0 {
		return "", "", errors.New("can't parse chart version string")
	}

	return x[:lastInd], x[lastInd+1:], nil
}
```

this func get the last index "-" of  the result of helm search repo or other command, 
it assume the last "-" seperate chartName and chartVersion ,
 but in my case it have the wrong result.

helm chart version  must be [SemVer 2](https://semver.org/) format,
 ref:  https://helm.sh/docs/chart_best_practices/conventions/#version-numbers

while  `1.2.3-alpha.1+123`  is a valid version for helm , ref  https://helm.sh/docs/chart_template_guide/function_list/#semver
```helm search repo xxx ```  return   ``` xxx-1.2.3-alpha.1+123```

in that case, if we use ```ChartAndVersion``` to get chartname and version ,  
 output is   ```xxx-1.2.3```  and ```alpha.1+123```
which is invalid.

i think this is a bug.

i have solution to fix it, i can push a merge request if needed.

### PR DESCRIPTION
**Pull request by denganliang**
Fixes #95

### CODE REVIEW

**Comment by hdm23061993** [comment]
You can use regex
https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

**Comment by denganliang** [comment]
> You can use regex https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

there have some charts that dose not fullly meet the semver2, for example:
https://artifacthub.io/packages/helm/cert-manager/cert-manager
` helm install my-release --namespace cert-manager --version v1.10.0 jetstack/cert-manager`
the version is v1.10.0 , I did not find a way to handle it with regex.

**Comment by undera** [comment]
Yes, I would also suggest using a regex, it would be more reliable than custom parsing logic.

**Comment by undera** [comment]
Adding `v?` to a version string would allow for optional "v" prefix

**Comment by denganliang** [comment]
Let me have a try, and I will update my code later.

**Comment by denganliang** [comment]
> Adding `v?` to a regex string would allow for optional "v" prefix

I use regex of this   https://semver.org/   and add v prefix.
See: https://regex101.com/r/vkijKf/1/
```
^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

**Pull request merged**
