### PR TITLE
Fix resource status not enhanced for calls to /api/k8s/{kind}/get route

### LINKED ISSUE #516: EnhanceStatus not properly called for GET calls to /api/k8s/{kind}/get
### Description

While looking into code for solution of #418, I think I found a bug where the status of resource kind is not "enhanced" because of a little pointer bug.
I suppose the status in result object should hold the same values as for GET calls to /api/helm/releases/{ns}/{name}/resources with query parameter health set to true. If that is the case, I'm going to submit a fix for it.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alessandrodetta**
## Changes Proposed

The pointer address returned from EnhanceStatus is now correctly set, following the same structure adopted in Resources function of /pkg/dashboard/handlers/helmHandlers.go

## Check List

- [x] The title of my pull request is a short description of the changes
- [x] This PR relates to some issue: Closes #516
- [ ] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

### CODE REVIEW

**Comment by undera** [comment]
After looking a bit into it, I don't see this code called at all. Did you find the use action when it's called?

**Comment by alessandrodetta** [comment]
@undera I just limited my search to backend while testing the REST API for understanding purposes. 

Now that I look into frontend, I don't find any usage either. I don't know if it makes sense then to apply a fix to something that is still not in a final state or will be removed... I assumed that the endpoint was used because it existed. In any case, if you want to keep the call to EnhanceStatus inside the function, that piece of code will have to be fixed.

**Comment by undera** [comment]
Let's have it fixed anyway. Probably the endpoint should be marked as deprecated.

**Comment by undera** [comment]
Thank you for reporting this inconsistency!

**Comment by alessandrodetta** [comment]
> Let's have it fixed anyway. Probably the endpoint should be marked as deprecated.

> Thank you for reporting this inconsistency!

The pleasure is mine! Rather excuse me, I still have a lot to learn in order to contribute better in the project and on github in general :slightly_smiling_face:

**Pull request merged**
