### PR TITLE
Implement Uninstall modal with mocked data

### PR DESCRIPTION
**Pull request by ErezBiren**
Implement Uninstall Modal with mocked data

image

- [x] The title of my pull request is a short description of the changes
- [x] This PR relates to some issue: #257 
- [x] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

### CODE REVIEW

**Comment by ErezBiren** [comment]
@chad11111 please have a look.

**Comment by chad11111** [comment]
@ErezBiren please remove all unrelated files.

**Comment by chad11111** [comment]
@ErezBiren do you know why the tests are failing?

**Comment by ErezBiren** [comment]
> @ErezBiren do you know why the tests are failing?

no, I'll try to figure

**Pull request merged**
