### PR TITLE
Repo manage section

### PR DESCRIPTION
**Pull request by aman1376**
## Changes Proposed
Solved the conflict

Created repository manage section

Screenshot (55)

## Check List

- [X] The title of my pull request is a short description of the changes
- [X] This PR relates to some issue: 
- [X] I have documented the changes made (if applicable)
- [ ] I have covered the changes with unit tests

### CODE REVIEW

**Comment by aman1376** [comment]
@chad11111 have a look

**Comment by aman1376** [comment]
it is working fine on my system kindly check if you have pulled this branch as i have created a new branch and closed the pull request for the repo_manage_section branch

**Comment by aman1376** [comment]
@chad11111 have a look

**Comment by aman1376** [comment]
@chad11111 have a look

**Comment by chad11111** [comment]
@aman1376 is this pr for https://github.com/komodorio/helm-dashboard/issues/287?

**Comment by aman1376** [comment]
@chad11111 it's for #278 its similar to 287 but there is slight difference as in 287 on click of button there should be a dialogue box asking for input.

**Comment by aman1376** [comment]
@chad11111 it's for #278 its similar to 287 but there is slight difference as in 287 on click of button there should be a dialogue box asking for input.

**Comment by chad11111** [comment]
@aman1376 U need that pop-up bar here too

**Comment by chad11111** [comment]
@aman1376 This Pr should be for #287

thanks a lot!

**Comment by aman1376** [comment]
@chad11111 what about this pr

**Comment by aman1376** [comment]
in this pr we just needed to show how the repository manage section would look like and in #287 we need to add repositories to the list of repositories that we have.

**Comment by aman1376** [comment]
@chad11111 have a look

**Comment by aman1376** [comment]
@undera please have a lok

**Comment by aman1376** [comment]
@chad11111

**Pull request closed without merging**
